[package]
name = "rust_os"
version = "0.1.0"
authors = ["adirksen"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.8"
rlibc = "1.0.0"